import com.typesafe.sbt.packager.Keys.{bashScriptExtraDefines, dockerBaseImage, dockerRepository, dockerUpdateLatest}

lazy val microservice = Project("upscan-upload-proxy", file("."))
  .enablePlugins(play.sbt.PlayScala, SbtDistributablesPlugin)
  .settings(
    majorVersion := 0,
    scalaVersion := "2.13.12",
    libraryDependencies ++= AppDependencies.compile ++ AppDependencies.test,
    scalacOptions ++= Seq(
      "-Wconf:cat=unused-imports&src=.*routes.*:s", //silence import warnings in routes generated by comments
      "-Wconf:cat=unused&src=.*routes.*:s"          //silence  private val defaultPrefix in class Routes is never used
    )
  )
  .settings(resolvers += Resolver.jcenterRepo)
  .settings(bashScriptExtraDefines += """addJava "-Xms256M"""", bashScriptExtraDefines += """addJava "-Xmx2000M"""")
  .settings(PlayKeys.devSettings += "play.server.http.idleTimeout" -> "900 seconds")
  .settings(Seq(
    dockerUpdateLatest := true,
    dockerBaseImage := "artefacts.tax.service.gov.uk/hmrc-jre:latest",
    dockerRepository := Some("artefacts.tax.service.gov.uk")))
